version: '3.8'

services:
    dev:
        container_name: empatie-se_api_dev
        image: empatie-se-api-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: yarn start:debug
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - empatie-se-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    prod:
        container_name: empatie-se_api_prod
        image: empatie-se-api-prod:1.0.0
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command: yarn start:prod
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - empatie-se-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped

networks:
    empatie-se-network: